apiVersion: v2
name: profile-app
description: profile-app on the standard KOBIL DevOps surface
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.2.10

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.2.10

dependencies:
  - name: ks-chart-template-common
    version: 0.24.1
    repository: https://charts.kobil.com
